Did some further modifications to the make-process.
Added some aditional tests to configure.ac  


git-svn-id: http://192.168.1.80/svn/golgotha/worksrc@45 dfb5a597-25cf-0310-bb4d-ec683fa0f420

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -310,7 +310,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT CC CFLAGS ac_ct_CC SET_MAKE CPP CXXCPP X_CFLAGS X_PRE_LIBS X_LIBS X_EXTRA_LIBS EGREP build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT CC CFLAGS ac_ct_CC SET_MAKE CPP CXXCPP X_CFLAGS X_PRE_LIBS X_LIBS X_EXTRA_LIBS EGREP build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os LIBOBJS debug_or_release LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -865,6 +865,8 @@ Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
   --with-x                use the X Window System
+  --with-debug            Enable debugging support. Defaults to no
+
 
 Some influential environment variables:
   CXX         C++ compiler command
@@ -1296,8 +1298,12 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
 
+
+
+
 #AC_PREREQ(2.57)
           ac_config_headers="$ac_config_headers config.h"
+
 
 
 # Checks for programs.
@@ -4064,7 +4070,7 @@ fi
 
 fi
 
-#LIBS="-I$x_includes -L$x_libraries $LIBS"
+
 # Checks for libraries.
 # FIXME: Replace `main' with a function in `-lGL':
 #AC_CHECK_LIB([GL], [glEnable])
@@ -4141,7 +4147,70 @@ fi
 #AC_CHECK_LIB([gcc], [main])
 # FIXME: Replace `main' with a function in `-lm':
 #AC_CHECK_LIB([m], [sqrt])
-#AC_CHECK_LIB([stdc++], [__cxa_pure_virtual])
+
+echo "$as_me:$LINENO: checking for encrypt in -lcipher" >&5
+echo $ECHO_N "checking for encrypt in -lcipher... $ECHO_C" >&6
+if test "${ac_cv_lib_cipher_encrypt+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lcipher  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char encrypt ();
+int
+main ()
+{
+encrypt ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_cipher_encrypt=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_cipher_encrypt=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_cipher_encrypt" >&5
+echo "${ECHO_T}$ac_cv_lib_cipher_encrypt" >&6
+if test $ac_cv_lib_cipher_encrypt = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBCIPHER 1
+_ACEOF
+
+  LIBS="-lcipher $LIBS"
+
+fi
+
 
 # Checks for header files.
 
@@ -7886,6 +7955,26 @@ rm -f conftest.$ac_objext conftest.$ac_ext
 echo "$as_me:$LINENO: result: $ac_cv_mutex_recursive2" >&5
 echo "${ECHO_T}$ac_cv_mutex_recursive2" >&6
 
+debug_or_release="release"
+echo "$as_me:$LINENO: checking for --with-debug flag" >&5
+echo $ECHO_N "checking for --with-debug flag... $ECHO_C" >&6
+
+# Check whether --with-debug or --without-debug was given.
+if test "${with_debug+set}" = set; then
+  withval="$with_debug"
+  if test withval=yes; then
+#Passing something like -O2 -O0 results in the last one being effective
+  CXXFLAGS="$CXXFLAGS -O0 -D _DEBUG"
+  debug_or_release="debug"
+fi
+echo "$as_me:$LINENO: result: $debug_or_release" >&5
+echo "${ECHO_T}$debug_or_release" >&6
+
+else
+  echo "$as_me:$LINENO: result: $debug_or_release" >&5
+echo "${ECHO_T}$debug_or_release" >&6
+fi;
+
           ac_config_files="$ac_config_files Makefile"
 
 cat >confcache <<\_ACEOF
@@ -8528,6 +8617,7 @@ s,@target_cpu@,$target_cpu,;t t
 s,@target_vendor@,$target_vendor,;t t
 s,@target_os@,$target_os,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
+s,@debug_or_release@,$debug_or_release,;t t
 s,@LTLIBOBJS@,$LTLIBOBJS,;t t
 CEOF
 
